<?php

/**
 * @file
 * Functions to support site logic.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\rdf_skos\Entity\Concept;
use Drupal\rdf_skos\Entity\ConceptInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Sets the default content owner value.
 */
function investeu_core_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $concept = Concept::load('http://publications.europa.eu/resource/authority/corporate-body/ECFIN');
  $node = $form_state->getFormObject()->getEntity();

  if ($node instanceof NodeInterface
    && $concept instanceof ConceptInterface
    && $node->hasField('oe_content_content_owner')
    && $node->get('oe_content_content_owner')->isEmpty()
  ) {
    $form['oe_content_content_owner']['widget'][0]['target_id']['#default_value'] = $concept;
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function investeu_core_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $blinks = $breadcrumb->getLinks();
  $parameters = \Drupal::menuTree()->getCurrentRouteMenuTreeParameters('menu-breadcrumb-menu');
  $tree = \Drupal::menuTree()->load('menu-breadcrumb-menu', $parameters);
  $links = [];
  foreach ($tree as $item) {
    if (Url::fromRoute('<current>')->toString() == $item->link->getUrlObject()->toString()) {
      continue;
    }
    $link_entity = \Drupal::service('entity.repository')
      ->loadEntityByUuid('menu_link_content', $item->link->getDerivativeId());
    $translated_entity = \Drupal::service('entity.repository')->getTranslationFromContext($link_entity);
    $url = $translated_entity->link_override->first();
    $link_url = $item->link->getUrlObject();
    if ($url !== NULL) {
      $link_url = $url->isEmpty() ? $link_url : $url->getUrl();
    }

    $links[] = Link::fromTextAndUrl($item->link->getTitle(), $link_url);
  }
  foreach ($blinks as $blink) {
    $links[] = $blink;
  }

  $breadcrumb = new Breadcrumb();
  $breadcrumb->setLinks($links);
}
