<?php

/**
 * @file
 * Functions to support site logic.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\rdf_skos\Entity\Concept;
use Drupal\rdf_skos\Entity\ConceptInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Sets the default content owner value.
 */
function investeu_core_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $concept = Concept::load('http://publications.europa.eu/resource/authority/corporate-body/ECFIN');
  $node = $form_state->getFormObject()->getEntity();

  if ($node instanceof NodeInterface
    && $concept instanceof ConceptInterface
    && $node->hasField('oe_content_content_owner')
    && $node->get('oe_content_content_owner')->isEmpty()
  ) {
    $form['oe_content_content_owner']['widget'][0]['target_id']['#default_value'] = $concept;
  }
}

/**
 * {@inheritdoc}
 *
 * Keeps the selected facets when a views exposed form is submitted.
 */
function investeu_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $facets = \Drupal::request()->query->get('f');

  if (!empty($facets)) {
    // Iterate through facet query parameters and add hidden
    // form fields containing the facet values.
    foreach ($facets as $facet_key => $facet_value) {
      $form['f[' . $facet_key . ']'] = [
        '#type' => 'hidden',
        '#value' => $facet_value,
        '#weight' => -1,
      ];
    }

    $form['actions']['reset'] = [
      '#type' => 'submit',
      '#value' => t('Clear all'),
      '#submit' => ['investeu_core_form_views_exposed_form_filter_reset'],
    ];
  }
}

/**
 * {@inheritdoc}
 *
 * Clears the form values of an exposed form filter.
 */
function investeu_core_form_views_exposed_form_filter_reset(&$form, FormStateInterface $form_state) {
  $redirect = new RedirectResponse(Url::fromRoute('<current>')->toString());
  $redirect->send();
}

/**
 * {@inheritdoc}
 *
 * Alters the home breadcrumb label to Europa and adds
 * an additional link to the frontpage.
 */
function investeu_core_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $links = $breadcrumb->getLinks();
  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $link_europa = Url::fromUri('https://europa.eu/european-union/index_' . $langcode);

  if (!empty($links[0]) && $links[0] instanceof Link) {
    $links[0]->setText(t('Europa'))->setUrl($link_europa);
  }
  else {
    $breadcrumb->addLink(Link::fromTextAndUrl(t('Europa'), $link_europa));
  }

  $breadcrumb->addLink(Link::createFromRoute($site_name, '<front>'));
}
